### ISSUE TITLE
Pick Block Item Data

### ISSUE THREAD

**Issue by MichaelPriebe** [Articdive/ArticDataGenerator#6]
Not all blocks have items, but most (maybe all?) blocks have a pick block item, or the item selected when using the middle mouse button.

Examples:
lava_cauldron -> cauldron
white_candle_cake -> cake
potted_azalea_bush -> azalea

**Comment by Articdive** [comment]
I will have a look at this; excuse the long response somehow you slipped through my email filters.

**Comment by Articdive** [comment]
Added from now, Should you need more data please open issues here: https://github.com/Articdive/ArticData
